services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "80:80"
    networks:
      - network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports: 
      - "3000:3000"
    networks:
      - network

networks:
  network:
    driver: bridge