name: Test site for publicly known js vulnerabilities

on: 
    workflow_dispatch:
        
    pull_request:
        branches:
            -main
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://ecomp.co/"