name: testing out ssh

on:
  [workflow_dispatch]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        script: |
          docker exec ubuntu /bin/bash -c 'bash /root/script.sh'
