name: TruffleHog Scan

on:
  [push]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install TruffleHog
      run: pip install truffleHog
#
#    - name: Run TruffleHog
#      run: trufflehog --json .
#
#    - name: Check for secrets
#      run: |
#        if grep -q '"reason":' trufflehog_report.json; then
#          echo "Secrets detected! Failing the build."
#          exit 1
#        else
#          echo "No secrets found."
#        fi
#
#    - name: Upload TruffleHog report
#      uses: actions/upload-artifact@v3
#      with:
#        name: trufflehog-report
#        path: trufflehog_report.json
#
